// Generated by data binding compiler. Do not edit!
package com.example.conectacastellon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import com.example.conectacastellon.R;
import java.lang.Deprecated;
import java.lang.Object;

public abstract class LoginBinding extends ViewDataBinding {
  @NonNull
  public final EditText contrasenya;

  @NonNull
  public final Button entrainvitado;

  @NonNull
  public final Button iniciasesion;

  @NonNull
  public final LinearLayout lay;

  @NonNull
  public final ConstraintLayout layusu;

  @NonNull
  public final ImageView logoapp;

  @NonNull
  public final Button registrar;

  @NonNull
  public final EditText usuario;

  protected LoginBinding(Object _bindingComponent, View _root, int _localFieldCount,
      EditText contrasenya, Button entrainvitado, Button iniciasesion, LinearLayout lay,
      ConstraintLayout layusu, ImageView logoapp, Button registrar, EditText usuario) {
    super(_bindingComponent, _root, _localFieldCount);
    this.contrasenya = contrasenya;
    this.entrainvitado = entrainvitado;
    this.iniciasesion = iniciasesion;
    this.lay = lay;
    this.layusu = layusu;
    this.logoapp = logoapp;
    this.registrar = registrar;
    this.usuario = usuario;
  }

  @NonNull
  public static LoginBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup root,
      boolean attachToRoot) {
    return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.login, root, attachToRoot, component)
   */
  @NonNull
  @Deprecated
  public static LoginBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup root,
      boolean attachToRoot, @Nullable Object component) {
    return ViewDataBinding.<LoginBinding>inflateInternal(inflater, R.layout.login, root, attachToRoot, component);
  }

  @NonNull
  public static LoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.login, null, false, component)
   */
  @NonNull
  @Deprecated
  public static LoginBinding inflate(@NonNull LayoutInflater inflater, @Nullable Object component) {
    return ViewDataBinding.<LoginBinding>inflateInternal(inflater, R.layout.login, null, false, component);
  }

  public static LoginBinding bind(@NonNull View view) {
    return bind(view, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.bind(view, component)
   */
  @Deprecated
  public static LoginBinding bind(@NonNull View view, @Nullable Object component) {
    return (LoginBinding)bind(component, view, R.layout.login);
  }
}
